apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api-app
  namespace: infra
  labels:
    app: k8s-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-api
  template:
    metadata:
      labels:
        app: k8s-api
    spec:
      containers:
        - image: moto999999/k8s_api_rest:latest
          resources:
            requests:
              memory: "5000Mi"
              cpu: "1000m"
#            limits:
#              memory: "7000Mi"
#              cpu: "3000m"
          imagePullPolicy: Always
          name: k8s-api
          ports:
            - containerPort: 5000
              name: api
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-api
  namespace: infra-auto-remediate-api
  labels:
    app: k8s-api
spec:
  type: ClusterIP
  selector:
    app: k8s-api
  ports:
    - port: 80
      targetPort: 5000
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ingress-auto-remediate-api
#  namespace: infra-auto-remediate-api
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: k8s-tfm.tk
#      http:
#        paths:
#          - pathType: Prefix
#            backend:
#              service:
#                name: k8s-api
#                port:
#                  number: 80
#            path: /api
