apiVersion: v1
kind: Pod
metadata:
  name: terraform-gcp
  namespace: infra
spec:
  containers:
    - name: terraform-gcp
      image: moto999999/terraform_gcp
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /etc/gcp_credentials
          name: google-secret
          readOnly: true
        - mountPath: /certificates
          name: certificates
          readOnly: true
        - mountPath: /ssh_key
          name: ssh-key
          readOnly: true
  volumes:
    - name: google-secret
      secret:
        secretName: google-secret
    - name: certificates
      secret:
        secretName: certificates
    - name: ssh-key
      secret:
        secretName: ssh-key
