{
 "title": "Kubernetes cluster overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "duration",
    "query": "10m,30m,1h,2h,6h,12h,1d,2d,5d,14d,30d"
   },
   { "name": "node", "label": "Node", "query": { "query": "kubelet_node_name" } }
  ]
 },
 "panels": [
  {
   "title": "Cluster status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(node) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "RAM utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "API server status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{container=\"kube-apiserver\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "cluster node readiness",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(kube_node_status_condition{status=\"true\",condition=\"Ready\"}) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(100 - ((node_filesystem_avail_bytes{fstype!=\"rootfs\",mountpoint=~\"/\"} * 100) / node_filesystem_size_bytes{fstype!=\"rootfs\",mountpoint=~\"/\"}))",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "(100 - ((node_filesystem_avail_bytes{fstype!=\"rootfs\",mountpoint=~\"/|/mnt/disks/pv-disk\",kubernetes_node=\"master1\"} * 100) / node_filesystem_size_bytes{fstype!=\"rootfs\",mountpoint=~\"/|/mnt/disks/pv-disk\",kubernetes_node=\"master1\"}))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "RAM utilization over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc((1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "CPU Utilization over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (avg by(node) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Disk Utilization over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(100 - ((node_filesystem_avail_bytes{fstype!=\"rootfs\",mountpoint=~\"/\"} * 100) / node_filesystem_size_bytes{fstype!=\"rootfs\",mountpoint=~\"/\"}))",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "(100 - ((node_filesystem_avail_bytes{fstype!=\"rootfs\",mountpoint=~\"/mnt/disks/pv-disk\",kubernetes_node=\"master1\"} * 100) / node_filesystem_size_bytes{fstype!=\"rootfs\",mountpoint=~\"/mnt/disks/pv-disk\",kubernetes_node=\"master1\"}))"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory/Disk/PID Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(kube_node_status_condition{status=\"true\",condition=~\"MemoryPressure|PIDPressure|DiskPressure\",node=\"$node\"})",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Node $node load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load5 + on(instance) group_left(nodename) \nnode_uname_info{nodename=\"$node\"}",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "machine_cpu_cores{instance=\"$node\"}",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "$node disk usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum by (nodename,device) (node_filesystem_avail_bytes{mountpoint=~\"/|/mnt/.*\",fstype!=\"rootfs\"} * on(instance) group_left(nodename) node_uname_info{nodename=\"$node\"}))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Waiting/Terminated pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(namespace,reason) (kube_pod_container_status_terminated_reason{reason!=\"Completed\"} !=0 )",
     "legendFormat": "TERMINATED::{{reason}}::{{namespace}}"
    },
    {
     "expr": "count by(namespace,reason) (kube_pod_container_status_waiting_reason !=0 )",
     "legendFormat": "WAITING::{{reason}}::{{namespace}}"
    },
    {}
   ]
  }
 ]
}