apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-minio
  namespace: minio
spec:
  ingressClassName: nginx
  rules:
    - host: "{{ ingress.hosts.minio }}"
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001
            path: /
    - host: "{{ ingress.hosts.minio_console }}"
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9000
            path: /
