apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-monitoring
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
    - host: "{{ ingress.hosts.prometheus-server }}"
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: prometheus-operated
                port:
                  number: 9090
            path: /
    - host: "{{ ingress.hosts.alert-manager }}"
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: alertmanager-operated
                port:
                  number: 9093
            path: /
    - host: "{{ ingress.hosts.grafana }}"
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: prometheus-grafana
                port:
                  number: 80
            path: /
