mode: standalone

auth:
  rootUser: admin
  rootPassword: {{ minio.password.root }}

replicas: 1

persistence:
  size: 100Gi

provisioning:
  users:
    - accessKey: console
      secretKey: {{ minio.password.console }}

defaultBuckets: velero

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/minio/v2/metrics/cluster"
  prometheus.io/port: "9000"
