---
# loadbalancer info
lb: 
  lb_dns: ip_lb
  lb_port: 6443

k8s:
  version: 1.26.3

nfs_disk:
  partition: /dev/sdb
  path: /mnt/disks/pv-disk

nfs_sc:
  name: nfs

minio:
  password:
    root: admintemporal
    console: admintemporal

bastion:
  internal_ip: ip_bastion_internal

helm:
  path: /var/lib/snapd/snap/bin/helm