---
# loadbalancer info
lb: 
  ip: ip_lb
  port_apiserver: 6443

k8s:
  version: 1.26.5

nfs_disk:
  partition: /dev/sdb
  path: /mnt/disks/pv-disk

nfs_sc:
  name: nfs

minio:
  password:
    root: admintemporal
    console: admintemporal

bastion:
  internal_ip: ip_bastion_internal

helm:
  path: /var/lib/snapd/snap/bin/helm

ingress:
  hosts:
    prometheus_server: prometheus.k8s-tfm.tk
    alert_manager: prometheus-alertmanager.k8s-tfm.tk
    grafana: grafana.k8s-tfm.tk
    minio: minio.k8s-tfm.tk
    minio_console: minio-console.k8s-tfm.tk