---
# loadbalancer info
lb: 
  lb_dns: 34.149.8.234
  lb_port: 6443

nfs_disk:
  partition: /dev/sdb
  path: /mnt/disks/pv-disk

nfs_sc:
  name: nfs

minio:
  password:
    root: admintemporal
    console: admintemporal

bastion:
  internal_ip: 10.0.0.2

helm:
  path: /var/lib/snapd/snap/bin/helm