# Add Kubernetes YUM Repo on all K8S cluster nodes
- name: add Kubernetes YUM repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
  when: inventory_hostname in groups['kube_cluster'] or inventory_hostname in groups['bastion']

# Install kubectl on bastion
- name: install kubectl
  yum:
    name:
      - kubectl-{{ k8s.version }}
    state: present
  when: inventory_hostname in groups['bastion']

# Install kubelet on all K8S cluster nodes
- name: install kubelet and kubeadm
  yum:
    name:
      - "{{ item }}-{{ k8s.version }}"
    state: present
  with_items: 
    - kubelet
    - kubeadm
  when: inventory_hostname in groups['kube_cluster']

# Install epel-release on all K8S cluster nodes and bastion
- name: install epel-release
  yum:
    name:
      - epel-release
    state: present
  when: inventory_hostname in groups['kube_cluster'] or inventory_hostname in groups['bastion']

# Install helm
- name: Install helm
  shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['kube_cluster'] or inventory_hostname in groups['bastion']

# Start kubelet service on all K8S cluster nodes
- name: start kubelet
  service:
    name: kubelet
    enabled: yes
    state: started
  when: inventory_hostname in groups['kube_cluster']
