- name: Add ingress-nginx repo
  shell: "helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['bastion']

- name: Copy ingress routes to bastion
  template:
    src: configuration_files/ingress_values.yaml
    dest: "{{ ansible_env.HOME }}/ingress_values.yaml"
  when: inventory_hostname in groups['bastion']

- name: Install ingress-nginx
  shell: >
    helm install ingress-nginx ingress-nginx/ingress-nginx \
    -n ingress-nginx --create-namespace \
    --values {{ ansible_env.HOME }}/ingress_values.yaml
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['bastion']

- name: Wait for deployment
  shell: >
    kubectl wait --namespace ingress-nginx \
    --for=condition=ready pod \
    --selector=app.kubernetes.io/component=controller
  when: inventory_hostname in groups['bastion']
