apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controlPlaneEndpoint: "{{ lb.lb_dns }}:{{ lb.lb_port }}"
networking:
  podSubnet: "192.168.0.0/16" # --pod-network-cidr