apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: moto999999/api:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api
spec:
  ingressClassName: nginx
  rules:
    - host: api.k8s-tfm.tk
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 80
            path: /
